/**
 * @since 1.0.0
 */
import * as Schema from "effect/Schema"

const prefix = "@effect/ai-amazon-bedrock"

const makeIdentifier = (name: string) => `${prefix}/${name}`

/**
 * The foundation models supported by Amazon Bedrock.
 *
 * An up-to-date list can be generated by sampling multiple regions and
 * deduplicating. Regions are ordered by rough estimated popularity/volume:
 *
 * ```sh
 * for region in us-east-1 us-west-2 eu-west-1 ap-northeast-1 ap-southeast-1 eu-central-1 ap-south-1 us-east-2; do
 *   aws bedrock list-foundation-models --region "$region" --output json
 * done | jq -s '[.[].modelSummaries[].modelId] | unique | sort'
 * ```
 *
 * @since 1.0.0
 * @category schemas
 */
export const BedrockFoundationModelId = Schema.Literals([
  "ai21.jamba-1-5-large-v1:0",
  "ai21.jamba-1-5-mini-v1:0",
  "amazon.nova-2-lite-v1:0",
  "amazon.nova-2-lite-v1:0:256k",
  "amazon.nova-2-multimodal-embeddings-v1:0",
  "amazon.nova-2-sonic-v1:0",
  "amazon.nova-canvas-v1:0",
  "amazon.nova-lite-v1:0",
  "amazon.nova-lite-v1:0:24k",
  "amazon.nova-lite-v1:0:300k",
  "amazon.nova-micro-v1:0",
  "amazon.nova-micro-v1:0:128k",
  "amazon.nova-micro-v1:0:24k",
  "amazon.nova-premier-v1:0",
  "amazon.nova-premier-v1:0:1000k",
  "amazon.nova-premier-v1:0:20k",
  "amazon.nova-premier-v1:0:8k",
  "amazon.nova-premier-v1:0:mm",
  "amazon.nova-pro-v1:0",
  "amazon.nova-pro-v1:0:24k",
  "amazon.nova-pro-v1:0:300k",
  "amazon.nova-reel-v1:0",
  "amazon.nova-reel-v1:1",
  "amazon.nova-sonic-v1:0",
  "amazon.rerank-v1:0",
  "amazon.titan-embed-g1-text-02",
  "amazon.titan-embed-image-v1",
  "amazon.titan-embed-image-v1:0",
  "amazon.titan-embed-text-v1",
  "amazon.titan-embed-text-v1:2:8k",
  "amazon.titan-embed-text-v2:0",
  "amazon.titan-embed-text-v2:0:8k",
  "amazon.titan-image-generator-v2:0",
  "amazon.titan-tg1-large",
  "anthropic.claude-3-5-haiku-20241022-v1:0",
  "anthropic.claude-3-5-sonnet-20240620-v1:0",
  "anthropic.claude-3-5-sonnet-20241022-v2:0",
  "anthropic.claude-3-7-sonnet-20250219-v1:0",
  "anthropic.claude-3-haiku-20240307-v1:0",
  "anthropic.claude-3-haiku-20240307-v1:0:200k",
  "anthropic.claude-3-haiku-20240307-v1:0:48k",
  "anthropic.claude-3-sonnet-20240229-v1:0",
  "anthropic.claude-3-sonnet-20240229-v1:0:200k",
  "anthropic.claude-3-sonnet-20240229-v1:0:28k",
  "anthropic.claude-haiku-4-5-20251001-v1:0",
  "anthropic.claude-opus-4-1-20250805-v1:0",
  "anthropic.claude-opus-4-20250514-v1:0",
  "anthropic.claude-opus-4-5-20251101-v1:0",
  "anthropic.claude-opus-4-6-v1",
  "anthropic.claude-sonnet-4-20250514-v1:0",
  "anthropic.claude-sonnet-4-5-20250929-v1:0",
  "anthropic.claude-sonnet-4-6",
  "cohere.command-r-plus-v1:0",
  "cohere.command-r-v1:0",
  "cohere.embed-english-v3",
  "cohere.embed-english-v3:0:512",
  "cohere.embed-multilingual-v3",
  "cohere.embed-multilingual-v3:0:512",
  "cohere.embed-v4:0",
  "cohere.rerank-v3-5:0",
  "deepseek.r1-v1:0",
  "deepseek.v3-v1:0",
  "deepseek.v3.2",
  "google.gemma-3-12b-it",
  "google.gemma-3-27b-it",
  "google.gemma-3-4b-it",
  "luma.ray-v2:0",
  "meta.llama3-1-405b-instruct-v1:0",
  "meta.llama3-1-70b-instruct-v1:0",
  "meta.llama3-1-70b-instruct-v1:0:128k",
  "meta.llama3-1-8b-instruct-v1:0",
  "meta.llama3-1-8b-instruct-v1:0:128k",
  "meta.llama3-2-11b-instruct-v1:0",
  "meta.llama3-2-11b-instruct-v1:0:128k",
  "meta.llama3-2-1b-instruct-v1:0",
  "meta.llama3-2-1b-instruct-v1:0:128k",
  "meta.llama3-2-3b-instruct-v1:0",
  "meta.llama3-2-3b-instruct-v1:0:128k",
  "meta.llama3-2-90b-instruct-v1:0",
  "meta.llama3-2-90b-instruct-v1:0:128k",
  "meta.llama3-3-70b-instruct-v1:0",
  "meta.llama3-3-70b-instruct-v1:0:128k",
  "meta.llama3-70b-instruct-v1:0",
  "meta.llama3-8b-instruct-v1:0",
  "meta.llama4-maverick-17b-instruct-v1:0",
  "meta.llama4-scout-17b-instruct-v1:0",
  "minimax.minimax-m2",
  "minimax.minimax-m2.1",
  "minimax.minimax-m2.5",
  "mistral.devstral-2-123b",
  "mistral.magistral-small-2509",
  "mistral.ministral-3-14b-instruct",
  "mistral.ministral-3-3b-instruct",
  "mistral.ministral-3-8b-instruct",
  "mistral.mistral-7b-instruct-v0:2",
  "mistral.mistral-large-2402-v1:0",
  "mistral.mistral-large-2407-v1:0",
  "mistral.mistral-large-3-675b-instruct",
  "mistral.mistral-small-2402-v1:0",
  "mistral.mixtral-8x7b-instruct-v0:1",
  "mistral.pixtral-large-2502-v1:0",
  "mistral.voxtral-mini-3b-2507",
  "mistral.voxtral-small-24b-2507",
  "moonshot.kimi-k2-thinking",
  "moonshotai.kimi-k2.5",
  "nvidia.nemotron-nano-12b-v2",
  "nvidia.nemotron-nano-3-30b",
  "nvidia.nemotron-nano-9b-v2",
  "nvidia.nemotron-super-3-120b",
  "openai.gpt-oss-120b-1:0",
  "openai.gpt-oss-20b-1:0",
  "openai.gpt-oss-safeguard-120b",
  "openai.gpt-oss-safeguard-20b",
  "qwen.qwen3-235b-a22b-2507-v1:0",
  "qwen.qwen3-32b-v1:0",
  "qwen.qwen3-coder-30b-a3b-v1:0",
  "qwen.qwen3-coder-480b-a35b-v1:0",
  "qwen.qwen3-coder-next",
  "qwen.qwen3-next-80b-a3b",
  "qwen.qwen3-vl-235b-a22b",
  "stability.sd3-5-large-v1:0",
  "stability.stable-conservative-upscale-v1:0",
  "stability.stable-creative-upscale-v1:0",
  "stability.stable-fast-upscale-v1:0",
  "stability.stable-image-control-sketch-v1:0",
  "stability.stable-image-control-structure-v1:0",
  "stability.stable-image-core-v1:1",
  "stability.stable-image-erase-object-v1:0",
  "stability.stable-image-inpaint-v1:0",
  "stability.stable-image-remove-background-v1:0",
  "stability.stable-image-search-recolor-v1:0",
  "stability.stable-image-search-replace-v1:0",
  "stability.stable-image-style-guide-v1:0",
  "stability.stable-image-ultra-v1:1",
  "stability.stable-outpaint-v1:0",
  "stability.stable-style-transfer-v1:0",
  "twelvelabs.marengo-embed-2-7-v1:0",
  "twelvelabs.marengo-embed-3-0-v1:0",
  "twelvelabs.pegasus-1-2-v1:0",
  "writer.palmyra-vision-7b",
  "writer.palmyra-x4-v1:0",
  "writer.palmyra-x5-v1:0",
  "zai.glm-4.7",
  "zai.glm-4.7-flash",
  "zai.glm-5"
])

/**
 * @since 1.0.0
 * @category schemas
 */
export type BedrockFoundationModelId = typeof BedrockFoundationModelId.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class CachePointBlock extends Schema.Class<CachePointBlock>(makeIdentifier("CachePointBlock"))({
  type: Schema.Literal("default")
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const DocumentFormat = Schema.Literals([
  "csv",
  "doc",
  "docx",
  "html",
  "md",
  "pdf",
  "txt",
  "xls",
  "xlsx"
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type DocumentFormat = typeof DocumentFormat.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class DocumentBlock extends Schema.Class<DocumentBlock>(makeIdentifier("DocumentBlock"))({
  name: Schema.String
    .check(Schema.isPattern(/^[a-zA-Z0-9()[\]-]+(?: [a-zA-Z0-9()[\]-]+)*$/))
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(200)),
  format: DocumentFormat,
  source: Schema.Struct({
    bytes: Schema.NonEmptyString
  })
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailConverseImageBlock extends Schema.Class<GuardrailConverseImageBlock>(
  makeIdentifier("GuardrailConverseImageBlock")
)({
  format: Schema.Literals(["png", "jpg"]),
  source: Schema.Struct({
    bytes: Schema.NonEmptyString
  })
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailConverseTextBlock extends Schema.Class<GuardrailConverseTextBlock>(
  makeIdentifier("GuardrailConverseTextBlock")
)({
  text: Schema.String,
  qualifiers: Schema.optionalKey(Schema.Array(Schema.Literals(["guard_content", "grounding_source", "query"])))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const GuardrailConverseContentBlock = Schema.Union([
  GuardrailConverseImageBlock,
  GuardrailConverseTextBlock
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type GuardrailConverseContentBlock = typeof GuardrailConverseContentBlock.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export const ImageFormat = Schema.Literals(["gif", "jpeg", "png", "webp"])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ImageFormat = typeof ImageFormat.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class ImageBlock extends Schema.Class<ImageBlock>(makeIdentifier("ImageBlock"))({
  format: ImageFormat,
  source: Schema.Struct({
    bytes: Schema.NonEmptyString
  })
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class JsonBlock extends Schema.Class<JsonBlock>(makeIdentifier("JsonBlock"))({
  json: Schema.Unknown
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ReasoningContentBlock = Schema.Union([
  Schema.Struct({
    reasoningText: Schema.Struct({
      text: Schema.String,
      signature: Schema.optionalKey(Schema.String)
    })
  }),
  Schema.Struct({
    redactedContent: Schema.String
  })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ReasoningContentBlock = typeof ReasoningContentBlock.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class VideoBlock extends Schema.Class<VideoBlock>(makeIdentifier("VideoBlock"))({
  format: Schema.Literals(["flv", "mkv", "mov", "mp4", "mpg", "mpeg", "three_gp", "webm"]),
  source: Schema.Union([
    Schema.Struct({
      bytes: Schema.NonEmptyString
    }),
    Schema.Struct({
      s3Location: Schema.Struct({
        uri: Schema.String
          .check(Schema.isPattern(/^s3:\/\/[a-z0-9][.\-a-z0-9]{1,61}[a-z0-9](\/.*)?$/))
          .check(Schema.isMinLength(1))
          .check(Schema.isMaxLength(1024)),
        bucketOwner: Schema.optionalKey(
          Schema.String.check(Schema.isPattern(/^[0-9]{12}$/))
        )
      })
    })
  ])
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolResultBlock extends Schema.Class<ToolResultBlock>(makeIdentifier("ToolResultBlock"))({
  content: Schema.Array(Schema.Union([
    Schema.Struct({ document: DocumentBlock }),
    Schema.Struct({ image: ImageBlock }),
    Schema.Struct({ text: Schema.String }),
    Schema.Struct({ json: JsonBlock }),
    Schema.Struct({ video: VideoBlock })
  ])),
  toolUseId: Schema.String
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/))
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64)),
  status: Schema.optionalKey(Schema.Literals(["success", "error"]))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolUseBlock extends Schema.Class<ToolUseBlock>(makeIdentifier("ToolUseBlock"))({
  name: Schema.String
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/))
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64)),
  input: Schema.Unknown,
  toolUseId: Schema.String
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/))
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ContentBlock = Schema.Union([
  Schema.Struct({ cachePoint: CachePointBlock }),
  Schema.Struct({ document: DocumentBlock }),
  Schema.Struct({ guardContent: GuardrailConverseContentBlock }),
  Schema.Struct({ image: ImageBlock }),
  Schema.Struct({ reasoningContent: ReasoningContentBlock }),
  Schema.Struct({ text: Schema.String }),
  Schema.Struct({ toolResult: ToolResultBlock }),
  Schema.Struct({ toolUse: ToolUseBlock }),
  Schema.Struct({ video: VideoBlock })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ContentBlock = typeof ContentBlock.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class Message extends Schema.Class<Message>(makeIdentifier("Message"))({
  role: Schema.Literals(["user", "assistant"]),
  content: Schema.Array(ContentBlock)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseOutput extends Schema.Class<ConverseOutput>(makeIdentifier("ConverseOutput"))({
  message: Message
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseMetrics extends Schema.Class<ConverseMetrics>(makeIdentifier("ConverseMetrics"))({
  latencyMs: Schema.DurationFromMillis
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailContentFilter extends Schema.Class<GuardrailContentFilter>(
  makeIdentifier("GuardrailContentFilter")
)({
  type: Schema.Literals(["HATE", "INSULTS", "MISCONDUCT", "PROMPT_ATTACK", "SEXUAL", "VIOLENCE"]),
  action: Schema.Literals(["BLOCKED", "NONE"]),
  confidence: Schema.Literals(["NONE", "LOW", "MEDIUM", "HIGH"]),
  detected: Schema.optionalKey(Schema.Boolean),
  filterStrength: Schema.optionalKey(Schema.Literals(["NONE", "LOW", "MEDIUM", "HIGH"]))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailContentPolicyAssessment extends Schema.Class<GuardrailContentPolicyAssessment>(
  makeIdentifier("GuardrailContentPolicyAssessment")
)({
  filters: Schema.Array(GuardrailContentFilter)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailContextualGroundingFilter extends Schema.Class<GuardrailContextualGroundingFilter>(
  makeIdentifier("GuardrailContextualGroundingFilter")
)({
  type: Schema.Literals(["GROUNDING", "RELEVANCE"]),
  action: Schema.Literals(["BLOCKED", "NONE"]),
  score: Schema.Number.check(Schema.isBetween({ minimum: 0, maximum: 1 })),
  threshold: Schema.Number.check(Schema.isBetween({ minimum: 0, maximum: 1 })),
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailContextualGroundingPolicyAssessment
  extends Schema.Class<GuardrailContextualGroundingPolicyAssessment>(
    makeIdentifier("GuardrailContextualGroundingPolicyAssessment")
  )({
    filters: Schema.optionalKey(Schema.Array(GuardrailContextualGroundingFilter))
  })
{}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailImageCoverage extends Schema.Class<GuardrailImageCoverage>(
  makeIdentifier("GuardrailImageCoverage")
)({
  guarded: Schema.optionalKey(Schema.Int),
  total: Schema.optionalKey(Schema.Int)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailTextCharactersCoverage extends Schema.Class<GuardrailTextCharactersCoverage>(
  makeIdentifier("GuardrailTextCharactersCoverage")
)({
  guarded: Schema.optionalKey(Schema.Int),
  total: Schema.optionalKey(Schema.Int)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailCoverage extends Schema.Class<GuardrailCoverage>(makeIdentifier("GuardrailCoverage"))({
  images: Schema.optionalKey(GuardrailImageCoverage),
  textCharacters: Schema.optionalKey(GuardrailTextCharactersCoverage)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailUsage extends Schema.Class<GuardrailUsage>(makeIdentifier("GuardrailUsage"))({
  contentPolicyUnits: Schema.Int,
  contextualGroundingPolicyUnits: Schema.Int,
  sensitiveInformationPolicyFreeUnits: Schema.Int,
  sensitiveInformationPolicyUnits: Schema.Int,
  topicPolicyUnits: Schema.Int,
  wordPolicyUnits: Schema.Int,
  contentPolicyImageUnits: Schema.optionalKey(Schema.Int)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailInvocationMetrics extends Schema.Class<GuardrailInvocationMetrics>(
  makeIdentifier("GuardrailInvocationMetrics")
)({
  guardrailCoverage: Schema.optionalKey(GuardrailCoverage),
  guardrailProcessingLatency: Schema.optionalKey(Schema.Number),
  usage: Schema.optionalKey(GuardrailUsage)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailPiiEntityFilter extends Schema.Class<GuardrailPiiEntityFilter>(
  makeIdentifier("GuardrailPiiEntityFilter")
)({
  type: Schema.Literals([
    "ADDRESS",
    "AGE",
    "AWS_ACCESS_KEY",
    "AWS_SECRET_KEY",
    "CA_HEALTH_NUMBER",
    "CA_SOCIAL_INSURANCE_NUMBER",
    "CREDIT_DEBIT_CARD_CVV",
    "CREDIT_DEBIT_CARD_EXPIRY",
    "CREDIT_DEBIT_CARD_NUMBER",
    "DRIVER_ID",
    "EMAIL",
    "INTERNATIONAL_BANK_ACCOUNT_NUMBER",
    "IP_ADDRESS",
    "LICENSE_PLATE",
    "MAC_ADDRESS",
    "NAME",
    "PASSWORD",
    "PHONE",
    "PIN",
    "SWIFT_CODE",
    "UK_NATIONAL_HEALTH_SERVICE_NUMBER",
    "UK_NATIONAL_INSURANCE_NUMBER",
    "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER",
    "URL",
    "USERNAME",
    "US_BANK_ACCOUNT_NUMBER",
    "US_BANK_ROUTING_NUMBER",
    "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER",
    "US_PASSPORT_NUMBER",
    "US_SOCIAL_SECURITY_NUMBER",
    "VEHICLE_IDENTIFICATION_NUMBER"
  ]),
  action: Schema.Literals(["ANONYMIZED", "BLOCKED", "NONE"]),
  match: Schema.String,
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailRegexFilter extends Schema.Class<GuardrailRegexFilter>(
  makeIdentifier("GuardrailRegexFilter")
)({
  action: Schema.Literals(["ANONYMIZED", "BLOCKED", "NONE"]),
  name: Schema.optionalKey(Schema.String),
  match: Schema.optionalKey(Schema.String),
  regex: Schema.optionalKey(Schema.String),
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailSensitiveInformationPolicyAssessment
  extends Schema.Class<GuardrailSensitiveInformationPolicyAssessment>(
    makeIdentifier("GuardrailSensitiveInformationPolicyAssessment")
  )({
    piiEntities: Schema.Array(GuardrailPiiEntityFilter),
    regexes: Schema.Array(GuardrailRegexFilter)
  })
{}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailTopic extends Schema.Class<GuardrailTopic>(makeIdentifier("GuardrailTopic"))({
  action: Schema.Literals(["BLOCKED", "NONE"]),
  name: Schema.String,
  type: Schema.Literal("DENY"),
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailTopicPolicyAssessment extends Schema.Class<GuardrailTopicPolicyAssessment>(
  makeIdentifier("GuardrailTopicPolicyAssessment")
)({
  topics: Schema.Array(GuardrailTopic)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailCustomWord extends Schema.Class<GuardrailCustomWord>(
  makeIdentifier("GuardrailCustomWord")
)({
  action: Schema.Literals(["BLOCKED", "NONE"]),
  match: Schema.String,
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailManagedWord extends Schema.Class<GuardrailManagedWord>(
  makeIdentifier("GuardrailManagedWord")
)({
  action: Schema.Literals(["BLOCKED", "NONE"]),
  match: Schema.String,
  type: Schema.Literal("PROFANITY"),
  detected: Schema.optionalKey(Schema.Boolean)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailWordPolicyAssessment extends Schema.Class<GuardrailWordPolicyAssessment>(
  makeIdentifier("GuardrailWordPolicyAssessment")
)({
  customWords: GuardrailCustomWord,
  managedWordLists: GuardrailManagedWord
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailAssessment extends Schema.Class<GuardrailAssessment>(makeIdentifier("GuardrailAssessment"))({
  contentPolicy: Schema.optionalKey(GuardrailContentPolicyAssessment),
  contextualGroundingPolicy: Schema.optionalKey(GuardrailContextualGroundingPolicyAssessment),
  invocationMetrics: Schema.optionalKey(GuardrailInvocationMetrics),
  sensitiveInformationPolicy: Schema.optionalKey(GuardrailSensitiveInformationPolicyAssessment),
  topicPolicy: Schema.optionalKey(GuardrailTopicPolicyAssessment),
  wordPolicy: Schema.optionalKey(GuardrailWordPolicyAssessment)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailTraceAssessment extends Schema.Class<GuardrailTraceAssessment>(
  makeIdentifier("GuardrailTraceAssessment")
)({
  actionReason: Schema.optionalKey(Schema.String),
  inputAssessment: Schema.optionalKey(Schema.Record(Schema.String, GuardrailAssessment)),
  modelOutput: Schema.optionalKey(Schema.Array(Schema.String)),
  outputAssessments: Schema.optionalKey(Schema.Record(Schema.String, GuardrailAssessment))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class PromptRouterTrace extends Schema.Class<PromptRouterTrace>(makeIdentifier("PromptRouterTrace"))({
  invokedModelId: Schema.optionalKey(
    Schema.String.check(
      Schema.isPattern(
        /^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model\/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2})|(arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{1,20}):(|[0-9]{12}):inference-profile\/[a-zA-Z0-9-:.]+)$/
      )
    )
  )
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseTrace extends Schema.Class<ConverseTrace>(makeIdentifier("ConverseTrace"))({
  guardrail: Schema.optionalKey(GuardrailTraceAssessment),
  promptRouter: Schema.optionalKey(PromptRouterTrace)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const IntZeroOrGreater = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))

/**
 * @since 1.0.0
 * @category schemas
 */
export class TokenUsage extends Schema.Class<TokenUsage>(makeIdentifier("TokenUsage"))({
  inputTokens: IntZeroOrGreater,
  outputTokens: IntZeroOrGreater,
  totalTokens: IntZeroOrGreater,
  cacheReadInputTokens: Schema.optionalKey(IntZeroOrGreater),
  cacheWriteInputTokens: Schema.optionalKey(IntZeroOrGreater)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const SystemContentBlock = Schema.Union([
  Schema.Struct({ cachePoint: CachePointBlock }),
  Schema.Struct({ guardContent: GuardrailConverseContentBlock }),
  Schema.Struct({ text: Schema.String.check(Schema.isMinLength(1)) })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type SystemContentBlock = typeof SystemContentBlock.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class GuardrailConfiguration extends Schema.Class<GuardrailConfiguration>(
  makeIdentifier("GuardrailConfiguration")
)({
  guardrailIdentifier: Schema.String
    .check(Schema.isMinLength(0))
    .check(Schema.isMaxLength(2048))
    .check(
      Schema.isPattern(/^(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail\/[a-z0-9]+))$/)
    ),
  guardrailVersion: Schema.String
    .check(Schema.isPattern(/^(([1-9][0-9]{0,7})|(DRAFT))$/)),
  trace: Schema.optionalKey(Schema.Literals(["enabled", "disabled", "enabled_full"]))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class InferenceConfiguration extends Schema.Class<InferenceConfiguration>(
  makeIdentifier("InferenceConfiguration")
)({
  maxTokens: Schema.optionalKey(Schema.Int.check(Schema.isGreaterThanOrEqualTo(1))),
  stopSequences: Schema.optionalKey(
    Schema.Array(Schema.String.check(Schema.isMinLength(1)))
      .check(Schema.isMaxLength(4))
  ),
  temperature: Schema.optionalKey(Schema.Number.check(Schema.isBetween({ minimum: 0, maximum: 1 }))),
  topP: Schema.optionalKey(Schema.Number.check(Schema.isBetween({ minimum: 0, maximum: 1 })))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class PerformanceConfiguration extends Schema.Class<PerformanceConfiguration>(
  makeIdentifier("PerformanceConfiguration")
)({
  latency: Schema.optionalKey(Schema.Literals(["standard", "optimized"]))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolSpecification extends Schema.Class<ToolSpecification>(
  makeIdentifier("ToolSpecification")
)({
  name: Schema.String
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64))
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/)),
  inputSchema: Schema.Struct({
    json: Schema.Record(Schema.String, Schema.Unknown)
  }),
  description: Schema.optionalKey(Schema.String.check(Schema.isMinLength(1)))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class Tool extends Schema.Class<Tool>(
  makeIdentifier("Tool")
)({
  cachePoint: Schema.optionalKey(CachePointBlock),
  toolSpec: Schema.optionalKey(ToolSpecification)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ToolChoice = Schema.Union([
  Schema.Struct({ any: Schema.Struct({}) }),
  Schema.Struct({ auto: Schema.Struct({}) }),
  Schema.Struct({
    tool: Schema.Struct({
      name: Schema.String
        .check(Schema.isMinLength(1))
        .check(Schema.isMaxLength(64))
        .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/))
    })
  })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ToolChoice = typeof ToolChoice.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolConfiguration extends Schema.Class<ToolConfiguration>(
  makeIdentifier("ToolConfiguration")
)({
  tools: Schema.Array(Tool).check(Schema.isMinLength(1)),
  toolChoice: Schema.optionalKey(ToolChoice)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseRequest extends Schema.Class<ConverseRequest>(makeIdentifier("ConverseRequest"))({
  modelId: Schema.String,
  messages: Schema.Array(Message),
  system: Schema.optionalKey(Schema.Array(SystemContentBlock)),
  toolConfig: Schema.optionalKey(ToolConfiguration),
  guardrailConfig: Schema.optionalKey(GuardrailConfiguration),
  inferenceConfig: Schema.optionalKey(InferenceConfiguration),
  performanceConfig: Schema.optionalKey(PerformanceConfiguration),
  promptVariables: Schema.optionalKey(Schema.Record(
    Schema.String,
    Schema.Struct({ text: Schema.String })
  )),
  requestMetadata: Schema.optionalKey(Schema.Record(
    Schema.String
      .check(Schema.isMinLength(1))
      .check(Schema.isMaxLength(256))
      .check(Schema.isPattern(/^[a-zA-Z0-9\s:_@$#=/+,-.]{1,256}$/)),
    Schema.String
      .check(Schema.isMinLength(0))
      .check(Schema.isMaxLength(256))
      .check(Schema.isPattern(/^[a-zA-Z0-9\s:_@$#=/+,-.]{0,256}$/))
  )),
  additionalModelRequestFields: Schema.optionalKey(Schema.Record(Schema.String, Schema.Unknown)),
  additionalModelResponseFieldPaths: Schema.optionalKey(
    Schema.Array(
      Schema.String.check(Schema.isMinLength(1)).check(Schema.isMaxLength(256))
    ).check(Schema.isMaxLength(10))
  )
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseResponse extends Schema.Class<ConverseResponse>(makeIdentifier("ConverseResponse"))({
  output: ConverseOutput,
  metrics: ConverseMetrics,
  usage: TokenUsage,
  stopReason: Schema.Literals([
    "content_filtered",
    "end_turn",
    "tool_use",
    "max_tokens",
    "stop_sequence",
    "guardrail_intervened"
  ]),
  trace: Schema.optionalKey(ConverseTrace),
  performanceConfig: Schema.optionalKey(Schema.Struct({
    latency: Schema.Literals(["standard", "optimized"])
  })),
  additionalModelResponseFields: Schema.optionalKey(Schema.Record(Schema.String, Schema.Unknown))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ReasoningContentBlockDelta = Schema.Union([
  Schema.Struct({ redactedContent: Schema.String }),
  Schema.Struct({ signature: Schema.String }),
  Schema.Struct({ text: Schema.String })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ReasoningContentBlockDelta = typeof ReasoningContentBlockDelta.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolUseBlockStart extends Schema.Class<ToolUseBlockStart>(
  makeIdentifier("ToolUseBlockStart")
)({
  name: Schema.String
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64))
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/)),
  toolUseId: Schema.String
    .check(Schema.isMinLength(1))
    .check(Schema.isMaxLength(64))
    .check(Schema.isPattern(/^[a-zA-Z0-9_-]+$/))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ContentBlockStart extends Schema.Class<ContentBlockStart>(
  makeIdentifier("ContentBlockStart")
)({
  toolUse: Schema.optionalKey(ToolUseBlockStart)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ContentBlockStartEvent extends Schema.Class<ContentBlockStartEvent>(
  makeIdentifier("ContentBlockStartEvent")
)({
  contentBlockIndex: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  start: ContentBlockStart
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ContentBlockStopEvent extends Schema.Class<ContentBlockStopEvent>(
  makeIdentifier("ContentBlockStopEvent")
)({
  contentBlockIndex: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ToolUseBlockDelta extends Schema.Class<ToolUseBlockDelta>(
  makeIdentifier("ToolUseBlockDelta")
)({
  input: Schema.String
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ContentBlockDelta = Schema.Union([
  Schema.Struct({ reasoningContent: ReasoningContentBlockDelta }),
  Schema.Struct({ text: Schema.String }),
  Schema.Struct({ toolUse: ToolUseBlockDelta })
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type ContentBlockDelta = typeof ContentBlockDelta.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class ContentBlockDeltaEvent extends Schema.Class<ContentBlockDeltaEvent>(
  makeIdentifier("ContentBlockDeltaEvent")
)({
  contentBlockIndex: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  delta: ContentBlockDelta
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class MessageStartEvent extends Schema.Class<MessageStartEvent>(
  makeIdentifier("MessageStartEvent")
)({
  role: Schema.Literals(["user", "assistant"])
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const StopReason = Schema.Literals([
  "end_turn",
  "tool_use",
  "max_tokens",
  "stop_sequence",
  "guardrail_intervened",
  "content_filtered"
])
/**
 * @since 1.0.0
 * @category schemas
 */
export type StopReason = typeof StopReason.Type

/**
 * @since 1.0.0
 * @category schemas
 */
export class MessageStopEvent extends Schema.Class<MessageStopEvent>(
  makeIdentifier("MessageStopEvent")
)({
  stopReason: StopReason,
  additionalModelResponseFields: Schema.optionalKey(Schema.Record(Schema.String, Schema.Unknown))
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseStreamMetrics extends Schema.Class<ConverseStreamMetrics>(
  makeIdentifier("ConverseStreamMetrics")
)({
  latencyMs: Schema.DurationFromMillis
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseStreamTrace extends Schema.Class<ConverseStreamTrace>(
  makeIdentifier("ConverseStreamTrace")
)({
  guardrail: Schema.optionalKey(GuardrailTraceAssessment),
  promptRouter: Schema.optionalKey(PromptRouterTrace)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export class ConverseStreamMetadataEvent extends Schema.Class<ConverseStreamMetadataEvent>(
  makeIdentifier("ConverseStreamMetadataEvent")
)({
  metrics: ConverseStreamMetrics,
  usage: TokenUsage,
  performanceConfig: Schema.optionalKey(PerformanceConfiguration),
  trace: Schema.optionalKey(ConverseStreamTrace)
}) {}

/**
 * @since 1.0.0
 * @category schemas
 */
export const ConverseResponseStreamEvent = Schema.Union([
  Schema.Struct({ messageStart: MessageStartEvent }).annotate({ title: "MessageStartEvent" }),
  Schema.Struct({ messageStop: MessageStopEvent }).annotate({ title: "MessageStopEvent" }),
  Schema.Struct({ contentBlockStart: ContentBlockStartEvent }).annotate({ title: "ContentBlockStartEvent" }),
  Schema.Struct({ contentBlockDelta: ContentBlockDeltaEvent }).annotate({ title: "ContentBlockDeltaEvent" }),
  Schema.Struct({ contentBlockStop: ContentBlockStopEvent }).annotate({ title: "ContentBlockStopEvent" }),
  Schema.Struct({ metadata: ConverseStreamMetadataEvent }).annotate({ title: "ConverseStreamMetadataEvent" }),
  Schema.Struct({
    internalServerException: Schema.Record(Schema.String, Schema.Unknown)
  }).annotate({ title: "InternalServerException" }),
  Schema.Struct({
    modelStreamErrorException: Schema.Record(Schema.String, Schema.Unknown)
  }).annotate({ title: "ModelStreamErrorException" }),
  Schema.Struct({
    serviceUnavailableException: Schema.Record(Schema.String, Schema.Unknown)
  }).annotate({ title: "ServiceUnavailableException" }),
  Schema.Struct({
    throttlingException: Schema.Record(Schema.String, Schema.Unknown)
  }).annotate({ title: "ThrottlingException" }),
  Schema.Struct({
    validationException: Schema.Record(Schema.String, Schema.Unknown)
  }).annotate({ title: "ValidationException" })
]).annotate({ title: "ConverseResponseStreamEvent" })

/**
 * @since 1.0.0
 * @category models
 */
export type ConverseResponseStreamEvent = typeof ConverseResponseStreamEvent.Type
